# Generated by Django 5.0 on 2023-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptTopup',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('partnerid', models.IntegerField(blank=True, db_column='PartnerId', null=True)),
                ('topup', models.CharField(blank=True, db_column='Topup', max_length=20, null=True)),
                ('currentbalance', models.CharField(blank=True, db_column='CurrentBalance', max_length=10, null=True)),
                ('createdtime', models.DateTimeField(blank=True, db_column='CreatedTime', null=True)),
                ('updatedtime', models.DateTimeField(blank=True, db_column='UpdatedTime', null=True)),
            ],
            options={
                'db_table': 'opt_topup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpCallPartner202312',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('sms', models.CharField(blank=True, db_column='Sms', max_length=10, null=True)),
                ('responseid', models.CharField(blank=True, db_column='ResponseId', max_length=50, null=True)),
                ('createdtime', models.DateTimeField(db_column='CreatedTime')),
                ('result', models.CharField(blank=True, db_column='Result', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('hangupcausecode', models.IntegerField(blank=True, db_column='HangupCauseCode', null=True)),
                ('hangupcausedesc', models.CharField(blank=True, db_column='HangupCauseDesc', max_length=100, null=True)),
                ('billsec', models.IntegerField(blank=True, db_column='BillSec', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('answersec', models.IntegerField(blank=True, db_column='AnswerSec', null=True)),
                ('partnerid', models.IntegerField(blank=True, db_column='PartnerId', null=True)),
                ('partnerresponsecode', models.CharField(blank=True, db_column='PartnerResponseCode', max_length=50, null=True)),
                ('partnerresponsedesc', models.CharField(blank=True, db_column='PartnerResponseDesc', max_length=20, null=True)),
            ],
            options={
                'db_table': 'otp_call_partner_202312',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpCallPartner202401',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('sms', models.CharField(blank=True, db_column='Sms', max_length=10, null=True)),
                ('responseid', models.CharField(blank=True, db_column='ResponseId', max_length=50, null=True)),
                ('createdtime', models.DateTimeField(db_column='CreatedTime')),
                ('result', models.CharField(blank=True, db_column='Result', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('hangupcausecode', models.IntegerField(blank=True, db_column='HangupCauseCode', null=True)),
                ('hangupcausedesc', models.CharField(blank=True, db_column='HangupCauseDesc', max_length=100, null=True)),
                ('billsec', models.IntegerField(blank=True, db_column='BillSec', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('answersec', models.IntegerField(blank=True, db_column='AnswerSec', null=True)),
                ('partnerid', models.IntegerField(blank=True, db_column='PartnerId', null=True)),
                ('partnerresponsecode', models.CharField(blank=True, db_column='PartnerResponseCode', max_length=50, null=True)),
                ('partnerresponsedesc', models.CharField(blank=True, db_column='PartnerResponseDesc', max_length=20, null=True)),
            ],
            options={
                'db_table': 'otp_call_partner_202401',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpCallVendor202312',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('sms', models.CharField(blank=True, db_column='Sms', max_length=10, null=True)),
                ('requestid', models.CharField(blank=True, db_column='RequestId', max_length=50, null=True)),
                ('partnerid', models.IntegerField(blank=True, db_column='PartnerId', null=True)),
                ('ip', models.CharField(blank=True, db_column='Ip', max_length=50, null=True)),
                ('typeof', models.IntegerField(blank=True, db_column='Typeof', null=True)),
                ('vendorid', models.IntegerField(blank=True, db_column='VendorId', null=True)),
                ('price', models.CharField(blank=True, db_column='Price', max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('vendorreponsecode', models.IntegerField(blank=True, db_column='VendorReponseCode', null=True)),
                ('vendorreponseid', models.CharField(blank=True, db_column='VendorReponseId', max_length=50, null=True)),
                ('vendorreponsedesc', models.CharField(blank=True, db_column='VendorReponseDesc', max_length=200, null=True)),
                ('partnerotpprice', models.CharField(blank=True, db_column='PartnerOtpPrice', max_length=10, null=True)),
                ('createdtime', models.DateTimeField(db_column='CreatedTime')),
            ],
            options={
                'db_table': 'otp_call_vendor_202312',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpCallVendor202401',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('sms', models.CharField(blank=True, db_column='Sms', max_length=10, null=True)),
                ('requestid', models.CharField(blank=True, db_column='RequestId', max_length=50, null=True)),
                ('partnerid', models.IntegerField(blank=True, db_column='PartnerId', null=True)),
                ('ip', models.CharField(blank=True, db_column='Ip', max_length=50, null=True)),
                ('typeof', models.IntegerField(blank=True, db_column='Typeof', null=True)),
                ('vendorid', models.IntegerField(blank=True, db_column='VendorId', null=True)),
                ('price', models.CharField(blank=True, db_column='Price', max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('vendorreponsecode', models.IntegerField(blank=True, db_column='VendorReponseCode', null=True)),
                ('vendorreponseid', models.CharField(blank=True, db_column='VendorReponseId', max_length=50, null=True)),
                ('vendorreponsedesc', models.CharField(blank=True, db_column='VendorReponseDesc', max_length=200, null=True)),
                ('partnerotpprice', models.CharField(blank=True, db_column='PartnerOtpPrice', max_length=10, null=True)),
                ('createdtime', models.DateTimeField(db_column='CreatedTime')),
            ],
            options={
                'db_table': 'otp_call_vendor_202401',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpPartner',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('accountname', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', db_column='AccountName', max_length=200, null=True)),
                ('sourcenumber', models.IntegerField(blank=True, db_column='SourceNumber', null=True)),
                ('ip', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', db_column='Ip', max_length=200, null=True)),
                ('ssecretkey', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='SsecretKey', max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('linkcallback', models.CharField(blank=True, db_column='LinkCallBack', max_length=200, null=True)),
                ('linkbody', models.TextField(blank=True, db_column='LinkBody', null=True)),
                ('vendorid', models.IntegerField(blank=True, db_column='VendorId', null=True)),
                ('limitbalance', models.CharField(blank=True, db_column='LimitBalance', db_comment='Tong tien KH co the su dung', max_length=20, null=True)),
                ('price', models.CharField(blank=True, db_column='Price', db_comment='Gia 1 otp', max_length=10, null=True)),
                ('currentbalance', models.CharField(blank=True, db_column='CurrentBalance', db_comment='Tong tien KH da su dung', max_length=20, null=True)),
                ('todayconsumption', models.CharField(blank=True, db_column='TodayConsumption', db_comment='Tong tien KH su dung trong ngay', max_length=20, null=True)),
                ('typemoney', models.IntegerField(blank=True, db_column='TypeMoney', db_comment='0: VND; 1: USD', null=True)),
            ],
            options={
                'db_table': 'otp_partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpVendor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('accountname', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', db_column='AccountName', max_length=200, null=True)),
                ('linkapi', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', db_column='LinkApi', max_length=200, null=True)),
                ('linkbody', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', db_column='LinkBody', null=True)),
                ('linktoken', models.CharField(blank=True, db_column='LinkToken', max_length=200, null=True)),
            ],
            options={
                'db_table': 'otp_vendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrefixTelco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('telco', models.CharField(blank=True, max_length=50, null=True)),
                ('khienhd', models.CharField(blank=True, max_length=20, null=True)),
                ('mtcvoiceotp', models.CharField(blank=True, max_length=20, null=True)),
                ('miltech', models.CharField(blank=True, max_length=20, null=True)),
                ('frs', models.CharField(blank=True, max_length=20, null=True)),
                ('number_3tech', models.CharField(blank=True, db_column='3tech', max_length=20, null=True)),
                ('number_1zvietnam', models.CharField(blank=True, db_column='1zvietnam', max_length=20, null=True)),
                ('fts', models.CharField(blank=True, max_length=20, null=True)),
                ('tel4vn', models.CharField(blank=True, max_length=20, null=True)),
                ('imedia', models.CharField(blank=True, max_length=5, null=True)),
                ('bluelink', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'prefix_telco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdtime', models.CharField(blank=True, db_column='CreatedTime', max_length=20, null=True)),
                ('transactionid', models.CharField(blank=True, db_column='TransactionId', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=10, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tmp',
                'managed': False,
            },
        ),
    ]
